version: '3.8'

services:
  ak-preschool:
    build: .
    container_name: ak-preschool
    ports:
      - "8081:80"
    volumes:
      - ./assets:/usr/share/nginx/html/assets
      - ./index.html:/usr/share/nginx/html/index.html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ak-preschool-network

  # Optional: Redis für Caching (für zukünftige Erweiterungen)
  redis:
    image: redis:alpine
    container_name: ak-preschool-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ak-preschool-network
    profiles:
      - cache

volumes:
  redis_data:

networks:
  ak-preschool-network:
    driver: bridge 